model:
  class_path: nablafx.system.GreyBoxSystem
  init_args:
    lr: 0.1
    use_callbacks: true
    log_media_every_n_steps: 3000

    model:
      class_path: nablafx.models.GreyBoxModel
      init_args:
        processors:
          - class_path: nablafx.processors.ParametricEQ
            init_args:
              sample_rate: 48000
              min_gain_db: -12.0
              max_gain_db: 12.0
              min_q_factor: 0.1
              max_q_factor: 10.0
              block_size: 128
              control_type: "static-cond"
          - class_path: nablafx.processors.Gain
            init_args:
              sample_rate: 48000
              min_gain_db: -40.0
              max_gain_db: 40.0
              control_type: "static-cond"
          - class_path: nablafx.processors.DCOffset
            init_args:
              sample_rate: 48000
              min_offset: -2.0
              max_offset: 2.0
              control_type: "static-cond"
          - class_path: nablafx.processors.StaticRationalNonlinearity
            init_args:
              sample_rate: 48000
              degrees: [6, 5]
              init_approx_func: "tanh"
          - class_path: nablafx.processors.Gain
            init_args:
              sample_rate: 48000
              min_gain_db: -40.0
              max_gain_db: 40.0
              control_type: "static-cond"
          - class_path: nablafx.processors.ParametricEQ
            init_args:
              sample_rate: 48000
              min_gain_db: -12.0
              max_gain_db: 12.0
              min_q_factor: 0.1
              max_q_factor: 10.0
              block_size: 128
              control_type: "static-cond"
          - class_path: nablafx.processors.Lowpass
            init_args:
              sample_rate: 48000
              min_cutoff_freq: 20000
              max_cutoff_freq: 20000
              min_q_factor: 0.7
              max_q_factor: 0.7
              block_size: 128
              control_type: "static"
        num_controls: 1
        stat_control_params_initial: "rnd"
        stat_cond_num_layers: 3
        stat_cond_hidden_dim: 16
        dyn_block_size: 128
        dyn_num_layers: 1
        dyn_cond_block_size: 128
        dyn_cond_num_layers: 1

    loss:
      class_path: nablafx.loss.WeightedMultiLoss
      init_args:
        losses:
          - loss:
              class_path: torch.nn.L1Loss
            weight: .5
            name: "l1"
          - loss:
              class_path: auraloss.freq.MultiResolutionSTFTLoss
            weight: .5
            name: "mrstft"
