model:
  class_path: nablafx.system.BlackBoxSystem
  init_args:
    lr: 0.01
    log_media_every_n_steps: 3000

    model:
      class_path: nablafx.models.BlackBoxModel
      init_args:
        processor:
          class_path: nablafx.s4.S4
          init_args:
            num_inputs: 1
            num_outputs: 1
            num_controls: 0
            num_blocks: 8
            s4_state_dim: 32
            channel_width: 16
            batchnorm: False
            residual: True
            direct_path: False
            cond_type: tfilm
            cond_block_size: 128
            cond_num_layers: 1
            act_type: tanh
            # take_side_chain: False
            s4_learning_rate: 0.01
            # film_take_batchnorm: True
            # take_residual_connection: True
            # convert_to_decibels: False
            # take_tanh: False
            # take_parametered_tanh: True
            # convert_to_amplitude: False

    loss:
      class_path: nablafx.loss.WeightedMultiLoss
      init_args:
        losses:
          - loss:
              class_path: torch.nn.L1Loss
            weight: .5
            name: "l1"
          - loss:
              class_path: auraloss.freq.MultiResolutionSTFTLoss
            weight: .5
            name: "mrstft"
