# Example 1: Simple replacement of your current TimeAndFrequencyDomainLoss
model:
  class_path: nablafx.system.BlackBoxSystem
  init_args:
    lr: 0.005
    log_media_every_n_steps: 3000

    model:
      class_path: nablafx.models.BlackBoxModel
      init_args:
        processor:
          class_path: nablafx.gcn.GCN
          init_args:
            # ... existing processor config ...

    loss:
      class_path: nablafx.loss.WeightedMultiLoss
      init_args:
        losses:
          - loss:
              class_path: torch.nn.L1Loss
            weight: 0.5
            name: "l1"
          - loss:
              class_path: auraloss.freq.MultiResolutionSTFTLoss
            weight: 0.5
            name: "mrstft"

---
# Example 2: More complex multi-loss setup
model:
  class_path: nablafx.system.BlackBoxSystem
  init_args:
    # ... other configs ...

    loss:
      class_path: nablafx.loss.WeightedMultiLoss
      init_args:
        losses:
          - loss:
              class_path: auraloss.time.ESRLoss
            weight: 0.4
            name: "esr"
          - loss:
              class_path: auraloss.time.DCLoss
            weight: 0.2
            name: "dc"
          - loss:
              class_path: auraloss.freq.MultiResolutionSTFTLoss
              init_args:
                fft_sizes: [1024, 2048, 512]
                hop_sizes: [256, 512, 128]
                win_lengths: [1024, 2048, 512]
            weight: 0.3
            name: "multi_stft"
          - loss:
              class_path: auraloss.freq.MelSTFTLoss
              init_args:
                sample_rate: 48000
                n_mels: 128
            weight: 0.1
            name: "mel_stft"

---
# Example 3: Audio-specific loss combination
model:
  class_path: nablafx.system.BlackBoxSystem
  init_args:
    # ... other configs ...

    loss:
      class_path: nablafx.loss.WeightedMultiLoss
      init_args:
        losses:
          # Time domain losses
          - loss:
              class_path: auraloss.time.ESRLoss
            weight: 0.3
            name: "esr"
          - loss:
              class_path: nablafx.loss.EDCLoss
              init_args:
                remove_dc: true
                min_db: -80
            weight: 0.1
            name: "edc"

          # Frequency domain losses
          - loss:
              class_path: auraloss.freq.MultiResolutionSTFTLoss
              init_args:
                fft_sizes: [2048, 1024, 512]
                hop_sizes: [512, 256, 128]
            weight: 0.4
            name: "mr_stft"

          # Perceptual losses
          - loss:
              class_path: auraloss.perceptual.FeatLoss
              init_args:
                model: "vgg19"
                layer: "conv4_4"
            weight: 0.2
            name: "perceptual"
