trainer:
  gradient_clip_val: null # gradient clip applied manually in training step
  max_steps: 451000

  logger:
    # class_path: pytorch_lightning.loggers.WandbLogger
    class_path: lightning.pytorch.loggers.wandb.WandbLogger
    init_args:
      entity: team-mcomunita-qmul
      project: nnlinafx-PARAM
      name: bb_LSTM-TVC-96_lr.001_td.5_fd.5
      save_dir: logs-scratch-02/multidrive-ffuzz/LSTM-TVC/bb_LSTM-TVC-96_lr.001_td.5_fd.5 # dir needs to already exist
      group: Multidrive-FFuzz_LSTM-TVC
      tags: ["Multidrive-FFuzz", "LSTM-TVC"]
  callbacks:
    # - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    - class_path: lightning.pytorch.callbacks.model_checkpoint.ModelCheckpoint
      init_args:
        save_last: true
        save_top_k: 1
        monitor: loss/val/tot
        every_n_train_steps: 3000
        filename: "{epoch}-{step}"
    # - class_path: pytorch_lightning.callbacks.ModelSummary
    - class_path: lightning.pytorch.callbacks.ModelSummary
      init_args:
        max_depth: 2
    # - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    # - class_path: pytorch_lightning.callbacks.EarlyStopping
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        monitor: "loss/val/tot"
        patience: 50
        verbose: true