model:
  class_path: nnlafx.system.GreyBoxSystem
  init_args:
    lr: 0.1
    log_media_every_n_steps: 3000
    
    model: 
      class_path: nnlafx.models.GreyBoxModel
      init_args:
        processors: 
          - class_path: nnlafx.processors.ParametricEQ
            init_args:
              sample_rate: 48000
              min_gain_db: -12.0
              max_gain_db: 12.0
              min_q_factor: 0.1
              max_q_factor: 10.0
              block_size: 128
              control_type: "static"
          - class_path: nnlafx.processors.Gain
            init_args:
              sample_rate: 48000
              min_gain_db: -40.0
              max_gain_db: 40.0
              control_type: "static"
          - class_path: nnlafx.processors.DCOffset
            init_args:
              sample_rate: 48000
              min_offset: -2.0
              max_offset: 2.0
              control_type: "static"
          - class_path: nnlafx.processors.PhaseInversion
            init_args:
              sample_rate: 48000
          - class_path: nnlafx.processors.StaticRationalNonlinearity
            init_args:
              sample_rate: 48000
              degrees: [6,5]
              init_approx_func: "tanh"
              lr_multiplier: 1 # 1 is best
          - class_path: nnlafx.processors.Gain
            init_args:
              sample_rate: 48000
              min_gain_db: -40.0
              max_gain_db: 40.0
              control_type: "static"
          - class_path: nnlafx.processors.ParametricEQ
            init_args:
              sample_rate: 48000
              min_gain_db: -12.0
              max_gain_db: 12.0
              min_q_factor: 0.1
              max_q_factor: 10.0
              block_size: 128
              control_type: "static"
          - class_path: nnlafx.processors.StaticFIRFilter
            init_args:
              sample_rate: 48000
              n_taps: 64
              hidden_dim: 32
              num_layers: 5
              w0_initial: 1000.0
              pretrained: "weights/static_fir_filter_t64-h32-l5.pt"
              lr_multiplier: 0.01 # 0.01 is best
          - class_path: nnlafx.processors.Lowpass
            init_args:
              sample_rate: 48000
              min_cutoff_freq: 20000
              max_cutoff_freq: 20000
              min_q_factor: 0.7
              max_q_factor: 0.7
              block_size: 128
              control_type: "static"
        num_controls: 0
        stat_control_params_initial: "rnd"
        stat_cond_num_layers: 3
        stat_cond_hidden_dim: 16
        dyn_block_size: 128
        dyn_num_layers: 1
        dyn_cond_block_size: 128
        dyn_cond_num_layers: 1

    loss:
      class_path: nnlafx.loss.TimeAndFrequencyDomainLoss
      init_args:
        time_domain_weight: .5
        frequency_domain_weight: .5

        time_domain_loss:
          class_path: torch.nn.L1Loss

        frequency_domain_loss:
          class_path: auraloss.freq.MultiResolutionSTFTLoss