model:
  class_path: nnlafx.system.BlackBoxSystem
  init_args:
    lr: 0.005
    log_media_every_n_steps: 3000
    
    model:
      class_path: nnlafx.models.BlackBoxModel
      init_args:
        processor:
          class_path: nnlafx.lstm.LSTM
          init_args:
            num_inputs: 1
            num_outputs: 1
            num_controls: 0
            hidden_size: 32
            num_layers: 1
            residual: true
            direct_path: false
            cond_type: null # null, fixed, tvcond
            cond_block_size: 128 # block size for tvcond
            cond_num_layers: 1 # number of lstm layers for tvcond

    loss:
      class_path: nnlafx.loss.TimeAndFrequencyDomainLoss
      init_args:
        time_domain_weight: .5
        frequency_domain_weight: .5

        time_domain_loss:
          class_path: torch.nn.L1Loss

        frequency_domain_loss:
          class_path: auraloss.freq.MultiResolutionSTFTLoss
