model:
  class_path: nablafx.system.BlackBoxSystemWithTBPTT
  init_args:
    lr: 0.001
    log_media_every_n_steps: 30000
    step_num_samples: 12000

    model:
      class_path: nablafx.models.BlackBoxModel
      init_args:
        processor:
          class_path: nablafx.lstm.LSTM
          init_args:
            num_inputs: 1
            num_outputs: 1
            num_controls: 0
            hidden_size: 96
            num_layers: 1
            residual: true
            direct_path: false
            cond_type: tvcond # null, fixed, tvcond
            cond_block_size: 128 # block size for tvcond
            cond_num_layers: 1 # number of lstm layers for tvcond

    loss:
      class_path: nablafx.loss.WeightedMultiLoss
      init_args:
        losses:
          - loss:
              class_path: torch.nn.L1Loss
            weight: 10
            name: "l1"
          - loss:
              class_path: auraloss.freq.MultiResolutionSTFTLoss
            weight: 1
            name: "mrstft"
